#!/bin/bash

# PUSH MODIFICATION IN MAIN
#git checkout main
#git add .
#git commit -m "$1"
#git push origin main

# PULL AND PUSH MODIFICATION IN EACH BRANCH
#git checkout main
#git pull origin main

models=ARPEGE ARPEGE-DDH AROME ERA5 ICON

for branch in ARPEGE ARPEGE-DDH AROME ERA5 ICON labadie; do

    echo "Mise à jour de $branch"
    git checkout $branch

    
    for file in LagrangianTraj_MF.ipynb .gitignore README.md;do
	git checkout main $branch "$file"
    done

    # Sync tutorial spécifique à la branche s'il existe dans main
    
    if [ $branch == "ARPEGE-DDH" ]; then
	git checkout main $branch DDH.ipynb 
    fi

    if [ $branch == "labadie" ];then
	git checkout main $branch Tutorial-*Valence.ipynb 
    else
        tutorial="Tutorial_${branch}.ipynb"
        git checkout main -- "$tutorial"
    
    fi

    git add .
    git commit -m "Sync files from main" 2>/dev/null || echo " -> Rien à commiter"
    git push origin $branch

done

git checkout main
echo "=== Terminé ! ==="
